#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1
PROG=/usr/sbin/drcom-auth-watchdog
CONF=/etc/config/drcom-auth

start_service() {
	[ -x "$PROG" ] || return 1
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 300 5 5
	procd_set_param file "$CONF"
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "drcom-auth"
}

reload_service() {
	stop
	start
}
